pub mod apply;
pub mod blueprint;
pub mod build;
pub mod builtins;
pub mod check;
mod discovery;
pub mod docs;
pub mod http;
pub mod install;
pub mod local;
pub mod mcp;
pub mod run;
pub mod search;
pub mod secret;
pub mod server;
pub mod skill;
mod ssh_identity;
pub mod upgrade;
