//! Release-bundled, offline skill distribution. Never replace user-edited files.
use std::{
    collections::BTreeMap,
    fs,
    io::IsTerminal,
    path::{Path, PathBuf},
    process::ExitCode,
};

mod remote;

use anyhow::{Context, bail};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

const RECEIPT: &str = ".submilli-skill.json";
const VERSION_FILE: &str = "VERSION";

/// Every file under `skills/submilli`, as `(relative path, content)`; generated by `build.rs`.
const FILES: &[(&str, &str)] = include!(concat!(env!("OUT_DIR"), "/skill_files.rs"));

#[derive(clap::Subcommand)]
pub enum SkillCmd {
    /// Install the skill bundled with this CLI (no network required).
    Install(Target),
    /// Refresh an installed, unmodified skill from this CLI's bundle.
    Update(Target),
    /// Check installation integrity and freshness; exit 1 if missing or different.
    Status(Target),
    /// Bring every unmodified installation for this user and project up to the
    /// newest released skill. Falls back to this CLI's bundle when offline.
    Sync,
}

#[derive(Clone, Copy, clap::ValueEnum)]
enum Agent {
    Claude,
    Codex,
    Cursor,
}

impl Agent {
    fn directory(self) -> &'static str {
        match self {
            Self::Claude => ".claude",
            Self::Codex => ".agents",
            Self::Cursor => ".cursor",
        }
    }

    /// The `--agent` spelling and the assistant's display name.
    fn names(self) -> (&'static str, &'static str) {
        match self {
            Self::Claude => ("claude", "Claude Code"),
            Self::Codex => ("codex", "Codex"),
            Self::Cursor => ("cursor", "Cursor"),
        }
    }

    /// Files a project carries when this assistant is used in it. Codex reads
    /// `AGENTS.md`, which Cursor and others honour too, so it is not claimed
    /// by anyone; only an assistant's own directory or instruction file counts.
    fn project_markers(self) -> &'static [&'static str] {
        match self {
            Self::Claude => &[".claude", "CLAUDE.md"],
            Self::Codex => &[".agents", ".codex"],
            Self::Cursor => &[".cursor", ".cursorrules"],
        }
    }

    /// The assistant a skill path belongs to, from its discovery directory.
    fn from_skill_path(path: &Path) -> Option<Self> {
        let directory = path.parent()?.parent()?.file_name()?.to_str()?;
        [Self::Claude, Self::Codex, Self::Cursor]
            .into_iter()
            .find(|agent| agent.directory() == directory)
    }

    /// The verifier subagent shipped beside the skill: where the assistant
    /// discovers custom agents (Codex keeps them under `.codex`, not
    /// `.agents`), and which bundled file it is.
    fn verifier(self) -> (&'static str, &'static str) {
        match self {
            Self::Claude => (
                ".claude/agents/submilli-verifier.md",
                "agents/submilli-verifier.md",
            ),
            Self::Cursor => (
                ".cursor/agents/submilli-verifier.md",
                "agents/submilli-verifier.md",
            ),
            Self::Codex => (
                ".codex/agents/submilli-verifier.toml",
                "agents/submilli-verifier.toml",
            ),
        }
    }
}

#[derive(clap::Args)]
pub struct Target {
    /// Assistant whose discovery directory to use.
    #[arg(long, value_enum)]
    agent: Agent,
    /// Install in this project instead of the user home directory.
    #[arg(long, value_name = "DIRECTORY")]
    project: Option<PathBuf>,
}

#[derive(Serialize, Deserialize)]
struct Receipt {
    schema: u32,
    cli_version: String,
    /// Absent in receipts written before skill releases were numbered.
    #[serde(default)]
    skill_version: u32,
    files: BTreeMap<String, String>,
    /// Files installed outside the skill directory (the verifier subagent),
    /// keyed by path relative to the install root, so an edited copy is
    /// recognized and preserved on update.
    #[serde(default)]
    companions: BTreeMap<String, String>,
}

/// A complete set of skill files from one origin: this CLI or a skill release.
struct Bundle {
    version: u32,
    origin: String,
    files: BTreeMap<String, String>,
}

impl Bundle {
    fn bundled() -> Self {
        let files: BTreeMap<String, String> = FILES
            .iter()
            .map(|(name, content)| ((*name).to_owned(), (*content).to_owned()))
            .collect();
        // A bundle without a readable VERSION never outranks a release.
        let version = files
            .get(VERSION_FILE)
            .and_then(|text| text.trim().parse().ok())
            .unwrap_or(0);
        Self {
            version,
            origin: format!("CLI {}", env!("CARGO_PKG_VERSION")),
            files,
        }
    }

    fn receipt(&self) -> Receipt {
        Receipt {
            schema: 1,
            cli_version: env!("CARGO_PKG_VERSION").to_owned(),
            skill_version: self.version,
            files: self
                .files
                .iter()
                .map(|(name, content)| (name.clone(), digest(content.as_bytes())))
                .collect(),
            companions: BTreeMap::new(),
        }
    }
}

#[derive(PartialEq)]
enum State {
    NotInstalled,
    Modified,
    Current,
    /// Installed from a skill release newer than the bundle compared against.
    Newer(u32),
    Outdated,
}

impl std::fmt::Display for State {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::NotInstalled => f.write_str("not installed"),
            Self::Modified => f.write_str("locally modified; preserved"),
            Self::Current => f.write_str("current"),
            Self::Newer(version) => write!(f, "current (skill release v{version})"),
            Self::Outdated => f.write_str("outdated; run submilli skill sync"),
        }
    }
}

pub fn execute(cmd: SkillCmd) -> anyhow::Result<ExitCode> {
    let target = match &cmd {
        SkillCmd::Install(t) | SkillCmd::Update(t) | SkillCmd::Status(t) => t,
        SkillCmd::Sync => return sync(),
    };
    let root = match &target.project {
        Some(path) => path.clone(),
        None => user_home().context("cannot locate home; use --project DIRECTORY")?,
    };
    let root = root
        .canonicalize()
        .with_context(|| format!("opening {}", root.display()))?;
    let path = root.join(target.agent.directory()).join("skills/submilli");
    check_ancestors(&root, &path)?;
    match cmd {
        SkillCmd::Status(_) => {
            let state = status(&path, &Bundle::bundled())?;
            println!(
                "{}: {state} (CLI {})",
                path.display(),
                env!("CARGO_PKG_VERSION")
            );
            Ok(match state {
                State::Current | State::Newer(_) => ExitCode::SUCCESS,
                _ => ExitCode::FAILURE,
            })
        }
        SkillCmd::Install(_) | SkillCmd::Update(_) => {
            let bundle = Bundle::bundled();
            install(&path, matches!(cmd, SkillCmd::Update(_)), &bundle)?;
            println!(
                "{}: skill v{} from {} is installed. Restart your assistant to reload it.",
                path.display(),
                bundle.version,
                bundle.origin
            );
            Ok(ExitCode::SUCCESS)
        }
        SkillCmd::Sync => unreachable!("handled before resolving a target"),
    }
}

/// Runs without flags so an assistant can call it before reading the skill,
/// whatever target the skill was installed with. Never fails the session:
/// an installation that cannot be refreshed is reported and left as it is.
fn sync() -> anyhow::Result<ExitCode> {
    let installs = managed_installs();
    if installs.is_empty() {
        println!("No Submilli skill installed by this CLI was found; nothing to sync.");
        return Ok(ExitCode::SUCCESS);
    }
    let bundled = Bundle::bundled();
    let target = match remote::newest_release(bundled.version) {
        Ok(Some(release)) => release,
        Ok(None) => bundled,
        Err(error) => {
            println!(
                "Skill release check skipped: {error:#}. Using {}.",
                bundled.origin
            );
            bundled
        }
    };
    for path in installs {
        match sync_one(&path, &target) {
            Ok(line) => println!("{}: {line}", path.display()),
            Err(error) => println!("{}: not synced: {error:#}", path.display()),
        }
    }
    if network_allowed()
        && let Some(tag) = super::upgrade::newer_release_hint()
    {
        println!("submilli {tag} is available; run `submilli upgrade` when convenient.");
    }
    Ok(ExitCode::SUCCESS)
}

/// One switch keeps a session entirely offline.
fn network_allowed() -> bool {
    std::env::var_os("SUBMILLI_SKILL_AUTOUPDATE").is_none_or(|value| value != "0")
}

fn sync_one(path: &Path, target: &Bundle) -> anyhow::Result<String> {
    let state = status(path, target)?;
    if state != State::Outdated {
        return Ok(state.to_string());
    }
    let skill_md_before = fs::read(path.join("SKILL.md")).ok();
    install(path, true, target)?;
    let reread = if fs::read(path.join("SKILL.md")).ok() == skill_md_before {
        "read references from disk as usual"
    } else {
        "SKILL.md changed: re-read it before continuing"
    };
    Ok(format!(
        "updated to skill v{} from {}; {reread}",
        target.version, target.origin
    ))
}

/// No network or mutation on ordinary invocations. Project copies and user
/// copies are checked so a CLI upgrade makes the update step discoverable.
pub fn warn_if_outdated() {
    if !std::io::stderr().is_terminal() {
        return;
    }
    let bundled = Bundle::bundled();
    for path in managed_installs() {
        if let Ok(receipt) = read_receipt(&path)
            && receipt.skill_version <= bundled.version
            && receipt.files != bundled.receipt().files
        {
            eprintln!(
                "Submilli skill at {} differs from this CLI. Run `submilli skill sync`. Local edits are preserved.",
                path.display()
            );
        }
    }
}

/// One line suggesting `skill install` to a developer who has just scaffolded
/// a package, naming the assistants their project shows signs of. Nothing is
/// installed: the user install writes outside the project and which assistant
/// they use is their call. `None` when a managed installation already exists
/// for this user or project.
pub fn adoption_hint(project: &Path) -> Option<String> {
    if !managed_installs().is_empty() {
        return None;
    }
    let roots: Vec<&Path> = project
        .ancestors()
        .scan(false, |done, dir| {
            if *done {
                return None;
            }
            *done = dir.join(".git").exists();
            Some(dir)
        })
        .collect();
    let detected: Vec<Agent> = [Agent::Claude, Agent::Codex, Agent::Cursor]
        .into_iter()
        .filter(|agent| {
            roots.iter().any(|root| {
                agent
                    .project_markers()
                    .iter()
                    .any(|marker| root.join(marker).exists())
            })
        })
        .collect();
    let hint = match detected.as_slice() {
        [] => "tip: if you use Claude Code, Codex or Cursor, `submilli skill install --agent <claude|codex|cursor>` teaches it to build packages and blueprints".to_string(),
        [agent] => {
            let (flag, name) = agent.names();
            format!(
                "tip: `submilli skill install --agent {flag}` teaches {name} to build packages and blueprints here (add `--project .` to commit it with the repo)"
            )
        }
        many => {
            let flags: Vec<&str> = many.iter().map(|agent| agent.names().0).collect();
            format!(
                "tip: `submilli skill install --agent <{}>` teaches your assistant to build packages and blueprints here (add `--project .` to commit it with the repo)",
                flags.join("|")
            )
        }
    };
    Some(hint)
}

/// Receipt-bearing installations under the user home and from the working
/// directory up to the enclosing repository root.
fn managed_installs() -> Vec<PathBuf> {
    let mut roots = Vec::new();
    if let Some(home) = user_home() {
        roots.push(home);
    }
    if let Ok(cwd) = std::env::current_dir() {
        for dir in cwd.ancestors() {
            roots.push(dir.to_path_buf());
            if dir.join(".git").exists() {
                break;
            }
        }
    }
    roots.sort();
    roots.dedup();
    let mut installs = Vec::new();
    for root in roots {
        for agent in [Agent::Claude, Agent::Codex, Agent::Cursor] {
            let path = root.join(agent.directory()).join("skills/submilli");
            if check_ancestors(&root, &path).is_ok() && read_receipt(&path).is_ok() {
                installs.push(path);
            }
        }
    }
    installs
}

fn user_home() -> Option<PathBuf> {
    std::env::var_os(if cfg!(windows) { "USERPROFILE" } else { "HOME" })
        .filter(|s| !s.is_empty())
        .map(PathBuf::from)
}

fn check_ancestors(root: &Path, path: &Path) -> anyhow::Result<()> {
    let mut current = root.to_path_buf();
    for component in path.strip_prefix(root)?.components() {
        current.push(component);
        match fs::symlink_metadata(&current) {
            Ok(meta) if !meta.is_dir() || meta.file_type().is_symlink() => {
                bail!("refusing non-directory or symlink {}", current.display())
            }
            Ok(_) => {}
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => return Err(e.into()),
        }
    }
    Ok(())
}

fn digest(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

fn read_receipt(path: &Path) -> anyhow::Result<Receipt> {
    let receipt_path = path.join(RECEIPT);
    let meta = fs::symlink_metadata(&receipt_path)
        .context("not a managed installation; move it aside before installing")?;
    if !meta.is_file() || meta.file_type().is_symlink() {
        bail!("invalid skill receipt");
    }
    let receipt: Receipt = serde_json::from_slice(&fs::read(receipt_path)?)?;
    if receipt.schema != 1 {
        bail!("unsupported skill receipt; upgrade the CLI");
    }
    Ok(receipt)
}

fn disk_files(root: &Path, dir: &Path, out: &mut BTreeMap<String, String>) -> anyhow::Result<()> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        let kind = entry.file_type()?;
        if kind.is_symlink() {
            bail!("refusing symlink {}", path.display());
        }
        if kind.is_dir() {
            disk_files(root, &path, out)?;
        } else if kind.is_file() {
            let name = path
                .strip_prefix(root)?
                .components()
                .map(|part| {
                    part.as_os_str()
                        .to_str()
                        .context("non-UTF-8 filename in installed skill")
                })
                .collect::<anyhow::Result<Vec<_>>>()?
                .join("/");
            if name != RECEIPT {
                out.insert(name, digest(&fs::read(path)?));
            }
        } else {
            bail!("unsupported file {}", path.display());
        }
    }
    Ok(())
}

fn status(path: &Path, target: &Bundle) -> anyhow::Result<State> {
    if !path.try_exists()? {
        return Ok(State::NotInstalled);
    }
    let receipt = read_receipt(path)?;
    let mut actual = BTreeMap::new();
    disk_files(path, path, &mut actual)?;
    if actual != receipt.files {
        return Ok(State::Modified);
    }
    Ok(if receipt.files == target.receipt().files {
        State::Current
    } else if receipt.skill_version > target.version {
        State::Newer(receipt.skill_version)
    } else {
        State::Outdated
    })
}

fn install(path: &Path, update: bool, bundle: &Bundle) -> anyhow::Result<()> {
    let parent = path.parent().context("skill target needs a parent")?;
    fs::create_dir_all(parent)?;
    // Serialize installers before inspecting the receipt. No automatic stale
    // lock deletion: another process may still be using it.
    let lock_path = parent.join(".submilli-install.lock");
    let _lock_file = fs::OpenOptions::new().write(true).create_new(true).open(&lock_path)
        .with_context(|| format!("cannot acquire {}; if a previous installer crashed, remove this lock only after confirming no installer is running", lock_path.display()))?;
    let _lock = InstallLock(lock_path);
    drop(_lock_file);
    let exists = path.try_exists()?;
    if update && !exists {
        bail!(
            "skill is not installed at {}; run skill install first",
            path.display()
        );
    }
    if exists {
        let state = status(path, bundle)?;
        if matches!(state, State::Current | State::Newer(_)) {
            return Ok(());
        }
        if state == State::Modified {
            bail!(
                "{}: {state}. Move this directory aside to keep your edits, then install again",
                path.display()
            );
        }
        if !update {
            bail!(
                "already installed; use skill update with the same --agent and --project options"
            );
        }
    }
    // Both renames stay on the same filesystem. The previous directory is kept
    // until the replacement succeeds; a failed second rename restores it.
    let staging = tempfile::Builder::new()
        .prefix(".submilli-stage-")
        .tempdir_in(parent)?;
    let next = staging.path().join("next");
    fs::create_dir(&next)?;
    for (name, content) in &bundle.files {
        let file = next.join(name);
        fs::create_dir_all(file.parent().context("bundled file needs a parent")?)?;
        fs::write(file, content)?;
    }
    let previous_receipt = if exists {
        read_receipt(path).ok()
    } else {
        None
    };
    let companion = Companion::plan(path, bundle, previous_receipt.as_ref())?;
    let mut receipt = bundle.receipt();
    if let Some(companion) = &companion {
        receipt.companions.insert(
            companion.relative.clone(),
            digest(companion.content.as_bytes()),
        );
    }
    fs::write(next.join(RECEIPT), serde_json::to_vec_pretty(&receipt)?)?;
    let previous = staging.path().join("previous");
    if exists {
        fs::rename(path, &previous)?;
    }
    if let Err(error) = fs::rename(&next, path) {
        if exists && let Err(restore) = fs::rename(&previous, path) {
            let recovery = staging.keep();
            bail!(
                "install failed: {error}; restore failed: {restore}; previous skill preserved in {}",
                recovery.join("previous").display()
            );
        }
        return Err(error.into());
    }
    if let Some(companion) = companion {
        companion.install()?;
    }
    Ok(())
}

/// The verifier subagent file for the installation's assistant.
struct Companion {
    relative: String,
    destination: PathBuf,
    content: String,
    /// Set when a file is already there that this CLI did not write, or that
    /// was edited since: it is left alone and reported.
    preserved: bool,
}

impl Companion {
    fn plan(
        skill_path: &Path,
        bundle: &Bundle,
        previous: Option<&Receipt>,
    ) -> anyhow::Result<Option<Self>> {
        let Some(agent) = Agent::from_skill_path(skill_path) else {
            return Ok(None);
        };
        let (relative, source) = agent.verifier();
        let Some(content) = bundle.files.get(source) else {
            return Ok(None);
        };
        let root = skill_path
            .ancestors()
            .nth(3)
            .context("skill path is too shallow")?;
        let destination = root.join(relative);
        let directory = destination.parent().context("companion needs a parent")?;
        check_ancestors(root, directory)?;
        let preserved = match fs::read(&destination) {
            Ok(existing) => {
                let recorded = previous.and_then(|receipt| receipt.companions.get(relative));
                recorded != Some(&digest(&existing)) && existing != content.as_bytes()
            }
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => false,
            Err(error) => return Err(error.into()),
        };
        Ok(Some(Self {
            relative: relative.to_owned(),
            destination,
            content: content.clone(),
            preserved,
        }))
    }

    fn install(self) -> anyhow::Result<()> {
        if self.preserved {
            println!(
                "{}: not written; an edited or unmanaged file is already there. Delete it to receive the bundled verifier.",
                self.destination.display()
            );
            return Ok(());
        }
        fs::create_dir_all(
            self.destination
                .parent()
                .context("companion needs a parent")?,
        )?;
        fs::write(&self.destination, self.content)?;
        Ok(())
    }
}

struct InstallLock(PathBuf);
impl Drop for InstallLock {
    fn drop(&mut self) {
        let _ = fs::remove_file(&self.0);
    }
}
