[package]
name = "submilli-blueprint"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
submilli-policy = { path = "../submilli-policy" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_path_to_error = { workspace = true }
serde_yml = { workspace = true }
saphyr-parser = { workspace = true }
regex = { workspace = true }
async-trait = { workspace = true }
url = { workspace = true }
base64 = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
