import { readFileSync } from "node:fs";

const SUBMILLI_SERVER = (process.env.SUBMILLI_SERVER_URL || "http://127.0.0.1:8128").replace(/\/$/, "");
const BLUEPRINT_NAME = "quickstart";

// In a real application: this customer ID would be something you fetch based on the signed-in user.
const customerId = "cus_northwind";

// In a real application, this code will be supplied by your code-writing agent
const agentCodeToRun = process.argv[2];
if (!agentCodeToRun) {
  fail("usage: node app.mjs PATH_TO_TYPESCRIPT_PROGRAM");
}

// The API token this application was given for the server.
const token = process.env.SUBMILLI_SERVER_TOKEN;
if (!token) {
  fail("error: SUBMILLI_SERVER_TOKEN is not set; export the token the server was started with.");
}

let code;
try {
  code = readFileSync(agentCodeToRun, "utf8");
} catch (error) {
  fail(`error: cannot read ${agentCodeToRun}: ${error.message}`);
}

let response;
try {
  response = await fetch(`${SUBMILLI_SERVER}/v1/execute`, {
    method: "POST",
    headers: {
      authorization: `Bearer ${token}`,
      "content-type": "application/json",
    },
    body: JSON.stringify({
      blueprint: BLUEPRINT_NAME,
      // this is the code generated by your agent
      code,
      variables: { customerId },
    }),
  });
} catch (error) {
  fail(`error: cannot reach submilli-server at ${SUBMILLI_SERVER}: ${error.message}`);
}

let body;
try {
  body = await response.json();
} catch (error) {
  fail(`error: submilli-server returned invalid JSON (HTTP ${response.status}): ${error.message}`);
}

if (!body || typeof body !== "object") fail("error: invalid response from submilli-server");
const message = body.message || body.error?.message || body.error || `HTTP ${response.status}`;
if (!response.ok) {
  if (response.status === 401 || response.status === 403) fail(`[refused] ${message}`);
  if (body.error === "invalid_request" || body.error?.kind === "invalid_request") {
    fail(`[invalid_request] ${message}`);
  }
  fail(`[server error] ${message}`);
}

for (const line of body.console ?? []) console.log(`[program] ${line}`);
if (body.error?.kind === "invalid_request") {
  fail(`[invalid_request] ${body.error.message}`);
}
// Released v0.2.0 reports policy denials as runtime_error with this diagnostic.
const isPolicyDenial = body.error?.kind === "permission_denied" ||
  (body.error?.kind === "runtime_error" && body.error.message?.startsWith("error: PermissionDeniedError: permission denied:"));
if (isPolicyDenial) {
  console.error(`[denied]  ${body.error.message}`);
  process.exit(1);
}
if (body.error) fail(`[error] ${body.error.kind}: ${body.error.message}`);
console.log(`[result]  ${body.result}`);

function fail(message) {
  console.error(message);
  process.exit(1);
}
