import { readFileSync } from "node:fs";

const SUBMILLI_SERVER = "http://127.0.0.1:8128";
const BLUEPRINT_NAME = "quickstart";

// The API token this application was given for the server.
const token = process.env.SUBMILLI_SERVER_TOKEN;
if (!token) {
  console.error("SUBMILLI_SERVER_TOKEN is not set: export the token the server was started with.");
  process.exit(1);
}

// In a real application: this customer ID would be something you fetch based on the signed-in user.
const customerId = "cus_northwind";

// In a real application, this code will be supplied by your code-writing agent
const agentCodeToRun = process.argv[2];

const response = await fetch(`${SUBMILLI_SERVER}/v1/execute`, {
  method: "POST",
  headers: {
    authorization: `Bearer ${token}`,
    "content-type": "application/json",
  },
  body: JSON.stringify({
    blueprint: BLUEPRINT_NAME,
    // this is the code generated by your agent
    code: readFileSync(agentCodeToRun, "utf8"),
    variables: { customerId },
  }),
});

const body = await response.json();
if (response.status === 401 || response.status === 403) {
  // The server did not accept the token, and nothing ran.
  console.error(`[refused] ${body.message}`);
  process.exit(1);
}
for (const line of body.console ?? []) console.log(`[program] ${line}`);
if (body.error) console.log(`[denied]  ${body.error.message}`);
else console.log(`[result]  ${body.result}`);
